/** @file "simple_crypto.h"
 *  @author Crypto Caballeros
 *  @brief Header file housing function prototypes for FIU's 2025 attempt at MITRE's eCTF
 *  @date 2025
 *
*/


#ifndef ECTF_CRYPTO_HW_H
#define ECTF_CRYPTO_HW_H
 
#include <stdint.h>
#include <stddef.h>
 
/******************************** MACRO DEFINITIONS ********************************/
 #define BLOCK_SIZE 16
 #define KEY_SIZE 16
 #define HASH_SIZE 32  // SHA-256 produces a 32-byte hash
 #define HMAC_BLOCK_SIZE 64 // SHA-256 block size
 #define OPAD 0x5c
 #define IPAD 0x36
 
/******************************** FUNCTION PROTOTYPES ********************************/

/** @brief Initialize the cryptographic hardware
 * 
 *  @note This must be called before using other crypto functions
 * 
 *  @return 0 on success, non-zero on failure
 */
int crypto_init(void);
 
/** @brief Decrypts ciphertext using hardware-accelerated AES-128-ECB
 *
 *  @param ciphertext A pointer to a buffer of length len containing the
 *           ciphertext to decrypt
 *  @param len The length of the ciphertext to decrypt. Must be a multiple of
 *           BLOCK_SIZE (16 bytes)
 *  @param key A pointer to a buffer of length KEY_SIZE (16 bytes) containing
 *           the key to use for decryption
 *  @param iv A pointer to buffer of length len containing the initialization 
 *          vector generated by TRNG
 *  @param plaintext A pointer to a buffer of length len where the resulting
 *           plaintext will be written to
 *
 *  @return 0 on success, -1 on bad length, other non-zero for other error
*/
int decrypt_sym(uint8_t *ciphertext, size_t len, uint8_t *key, uint8_t *iv, uint8_t *plaintext);
 
/** @brief Hashes arbitrary-length data wolfSSL SHA-256
 *
 *  @param data A pointer to a buffer of length len containing the data
 *           to be hashed
 *  @param len The length of the plaintext to hash
 *  @param hash_out A pointer to a buffer of length HASH_SIZE (32 bytes) where the resulting
 *           hash output will be written to
 *
 *  @return 0 on success, non-zero for other error
 */
int hash(void *data, size_t len, uint8_t *hash_out);

/** @brief Creates HMAC object using wolfSSL hash function
 * 
 *  @param key A pointer to a buffer of length key_len containing key for HMAC
 *  @param key_len The length of the key to be used for HMAC
 *  @param message A pointer to a buffer of length message_len containing message for HMAC
 *  @param message_len The length of message to be used for HMAC
 *  @param hmac_output The computed output of HMAC
 * 
 *  @return 0 if successful
 * 
 *  @note Standard HMAC implementation (H is the hash function, K is the key)
 *  HMAC(K,m) = H((K' ⊕ opad) || H((K' ⊕ ipad) || m))
 *  where K' is the key padded to block size and m is the message
 */
 int compute_hmac(uint8_t *key, size_t key_len, uint8_t *message, size_t message_len, uint8_t *hmac_output);


#endif // ECTF_CRYPTO_HW_H
