"""
*****FIU MITRE eCTF 2025********************************************
*                                                                  *
*    encoder.py                                                    *
*                                                                  *
*   Author: Crypto Caballeros                                      *
*   Date: 2025                                                     *
*   Description: Initializes the encoding prosees, preparing       *
*   frames to be transmitted securely.                             *
*                                                                  *
********************************************************************
"""

"""

*****FIU MITRE eCTF 2025*****

    encoder.py

Author: Crypto Caballeros
Date: 2025
Description: 

"""



########INCLUDES#########
import argparse
from os import urandom
import struct
import json
import hmac
import hashlib
from wolfcrypt.ciphers import Aes
# from Crypto.Cipher import AES
# from Crypto.Util.Padding import pad



class Encoder:
    def __init__(self, secrets: bytes):

        """""""""""""""""""""""""""""""""""""""

            --INITIALIZATION FUNCTION--

        :param secrets: Contents of the secrets file generated by
            --ectf25_design.gen_secrets--
            
        """""""""""""""""""""""""""""""""""""""

        # Load the json of the secrets file
        self.secrets = json.loads(secrets)

        # Extract encryption key for frame encryption
        self.encryption_key = bytes.fromhex(self.secrets["encryption_Key"])

        # Extract MAC key for HMAC
        self.MAC_key = bytes.fromhex(self.secrets["MAC_Key"])


    def encode(self, channel: int, frame: bytes, timestamp: int) -> bytes:
        """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
        
                     ***THE ENCODER FUNCTION***

        This will be called for every frame that needs to be encoded before being
        transmitted by the satellite to all listening TVs

        You **may not** change the arguments or returns of this function!

        :param channel:   32b unsigned channel number. Channel 0 is the emergency broadcast that must be decodable by all channels.
        
        :param frame:     Frame to encode. Max frame size is 64 bytes.
        
        :param timestamp: 64b timestamp to use for encoding. 

                
                        **TIMESTAMP NOTE** 
                        
            -This value may have no relation to the current timestamp, 
            so you should NOT compare it against the current time.
            
            -The timestamp is guaranteed to strictly monotonically increase (always go up) with subsequent calls to encode

        :returns: The encoded frame, which will be sent to the Decoder

        
        """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

        # Generate IV for encryption
        iv = urandom(16)   # 16 bytes for AES block size

        # Use stored encryption key
        aes = Aes(self.encryption_key, 2, iv) # AES-256
        # aes = AES.new(self.encryption_key, AES.MODE_CBC, iv) # AES-256

        # Pad and encrypt frame data
        padding_length = 16 - (len(frame) % 16)
        padded_data = frame + (b'\x00' * padding_length)
        # padded_data = pad(frame, AES.block_size)
        ciphertext = aes.encrypt(padded_data)

        # Generate HMAC for authentication
        # Combines channel, timestamp, IV, and ciphertext
        hmac_input = struct.pack("<IQ", channel, timestamp) + iv + ciphertext

        # Create HMAC using MAC_key
        auth_tag = hmac.new(self.MAC_key, hmac_input, hashlib.sha256).digest()
        
        encrypted_frame = iv + auth_tag + ciphertext

        return struct.pack("<IQ", channel, timestamp) + encrypted_frame