"""
Author: Crypto Caballeros
Date: 2025

This file generates subscriptions to be used in a satllite TV system.
"""

import argparse
import json
from pathlib import Path
import struct
import hashlib

from loguru import logger


def gen_subscription(
    secrets: bytes, device_id: int, start: int, end: int, channel: int
) -> bytes:
    """Generate the contents of a subscription.

    The output of this will be passed to the Decoder using ectf25.tv.subscribe

    :param secrets: Contents of the secrets file generated by ectf25_design.gen_secrets
    :param device_id: Device ID of the Decoder
    :param start: First timestamp the subscription is valid for
    :param end: Last timestamp the subscription is valid for
    :param channel: Channel to enable

    :return result: subscription data and signature for verifcation
    """

    # Load the json of the secrets file
    secrets = json.loads(secrets)

    # Extract the subscription key from secrets
    master_key = bytes.fromhex(secrets["subscription_Key"])

    # Check if requested channel is valid
    if channel not in secrets["channels"] and channel != 0:
        logger.error(f"Channel {channel} is not a valid channel in this deployment. Valid channels are: {secrets["channels"]}")
        raise ValueError(f"Invalid channel: {channel}")

    # Create data buffer to be signed (device_id, start time, end time, channel)
    # for subscription (packaged)
    data_buffer = struct.pack("<IQQI", device_id, start, end, channel)

    # Determine device ID size and convert to bytes (little-endian)
    device_id_bytes = struct.pack("<I", device_id)

    # Derive a device-specific key using the device ID
    device_key_input = master_key + device_id_bytes
    device_key = hashlib.sha256(device_key_input).digest() # Hash to mitigate tampering

    # Generate the HMAC signature for the subscription data
    # Simple HMAC construction: hash(device_key || data) 
    # Signature will be decyphered if decoder is valid
    hmac_input = device_key + data_buffer
    signature = hashlib.sha256(hmac_input).digest()

    # Subscription packed into data_buffer (signature added on). 
    # This will be sent to the decoder with ectf25.tv.subscribe
    result = data_buffer + signature

    return result


def parse_args():
    """Define and parse the command line arguments

    NOTE: Your design must not change this function
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Force creation of subscription file, overwriting existing file",
    )
    parser.add_argument(
        "secrets_file",
        type=argparse.FileType("rb"),
        help="Path to the secrets file created by ectf25_design.gen_secrets",
    )
    parser.add_argument(
        "subscription_file", 
        type=Path,
        help="Subscription output"
    )
    parser.add_argument(
        "device_id", 
        type=lambda x: int(x, 0), 
        help="Device ID of the update recipient."
    )
    parser.add_argument(
        "start", 
        type=lambda x: int(x, 0), 
        help="Subscription start timestamp"
    )
    parser.add_argument(
        "end", 
        type=int, 
        help="Subscription end timestamp"
    )
    parser.add_argument(
        "channel", 
        type=int, 
        help="Channel to subscribe to"
    )
    return parser.parse_args()


def main():
    """Main function of gen_subscription

    You will likely not have to change this function
    """
    # Parse the command line arguments
    args = parse_args()

    subscription = gen_subscription(
        args.secrets_file.read(), args.device_id, args.start, args.end, args.channel
    )

    # Print the generated subscription for your own debugging
    # Attackers will NOT have access to the output of this (although they may have
    # subscriptions in certain scenarios), but feel free to remove
    #
    # NOTE: Printing sensitive data is generally not good security practice
    logger.debug(f"Generated subscription: {subscription}")

    # Open the file, erroring if the file exists unless the --force arg is provided
    with open(args.subscription_file, "wb" if args.force else "xb") as f:
        f.write(subscription)

    # For your own debugging. Feel free to remove
    logger.success(f"Wrote subscription to {str(args.subscription_file.absolute())}")


if __name__ == "__main__":
    main()
